### ISSUE TITLE
Completeness rates are gone

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-tasking-manager#201]
The % does not change anymore: Bambari is 88% even though all the tasks are done, while Berbérati is 100% even though I unvalidated some tasks marked as finished.

**Comment by dodobas** [comment]
hi, it should be working now

the problem was SQLAlchemy module, when using SQLAlchemy version 0.8, there is an issue with event triggered behavior _before_update_ and the way it's setup in the current _master_

Only information I managed to dig out was this error message:

```
SAWarning: Attribute history events accumulated on 1 previously clean instances within inner-flush event handlers have been reset, and will not result in database updates. Consider using set_committed_value() within inner-flush event handlers to avoid this warning
```

I've downgraded SQLAlchemy to the 0.7.9, jobs completeness rated will be updated as usual at the moment a user updates a task.
