### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by oeon** [hotosm/osm-tasking-manager#50]
OSMTM is very easy to setup, but after the install/setup - what should be done next? I think some documentation describing how to setup a task-grid for custom jobs would be beneficial. I could not find any information on customization/setup from Internet searches or after briefly looking at the HOTOSM mailing list. Perhaps I am missing something - and I'm sure if I had greater programming skills, this could be obvious. If I can help with this issue, I would be glad to.

**Comment by pgiraud** [comment]
Hey Joe,
At first, the Tasking Manager was not intended to be installed on other servers. But I'm really glad to hear that some people are about to do so.
The information that is missing in the documentation is that you need to be an admin user in order to create and manage jobs.
Then, creating jobs should be self-explaining.

When I installed the application on hotosm server, I created an admin user manually. I used the SQLite Manager extension for Firefox. The db file is OSMTM.db in the application repository.
If a "more" automatic script is worth, please let me know. It shouldn't be difficult to write.

Anyway, thanks a lot for your feedbacks.

**Comment by oeon** [comment]
Pierre, with your help I changed my admin status and am in. I am now confused on how to enter the 'OSM relation' section - should I put the local system path to my .osm file, the relation number or the URL to the relation? Thanks for your guidance.

**Comment by pgiraud** [comment]
You're right, this one lacks explanations too.
You should put the relation number if know one. I just pushed a fix to add some help text.

Side note: I intend to add a "draw your polygon area yourself" feature.

**Comment by oeon** [comment]
Putting the relation number does not work for me, but perhaps my server is too small (Amazon micro). I tried my specific relation # and the example one given. Neither resulted with the desired effect...the progress indicator simply repeats. I feel that becomes a separate issue however and will close this comment as your help has resolved the original issue. *Thank you.
